draw_set_color(c_white)
draw_text(16, 16 * 1,				"Power:      " + string(bomb_power))
draw_text(16, 16 * 2,				"Timer:      " + string(bomb_timer))
draw_text(16, 16 * 3,				"Health:     " + string(hp))
draw_text(16, 16 * 4,				"Score:      " + string(score_point))
draw_text(16, 16 * 5,				"Next level: " + string(upgrade_score * bomb_power))

draw_text(16, room_height - 16 * 6, "UP:         Up")
draw_text(16, room_height - 16 * 5, "LEFT:       Left")
draw_text(16, room_height - 16 * 4, "DOWN:       Down")
draw_text(16, room_height - 16 * 3, "RIGHT:      Right")
draw_text(16, room_height - 16 * 2, "PLACE BOMB: Space")
